/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proxima.view;

import javax.swing.DefaultListModel;
import javax.swing.ListModel;



import com.proxima.model.*;

/**
 *
 * @author james
 */
public class ProximaUI extends javax.swing.JFrame {

    /**
     * Creates new form proximaUI
     */
    public ProximaUI() {
        dispatch = new Dispatch();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actorListPanel = new javax.swing.JPanel();
        hireListScrollPane = new javax.swing.JScrollPane();
        hireJList = new javax.swing.JList<>();
        driverListScrollPane = new javax.swing.JScrollPane();
        driverJList = new javax.swing.JList<>();
        hireLabel = new javax.swing.JLabel();
        driverLabel = new javax.swing.JLabel();
        assignDriverButton = new javax.swing.JButton();
        detailsPanel = new javax.swing.JPanel();
        detailsScrollPane = new javax.swing.JScrollPane();
        detailsTextArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actorListPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        hireJList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        // hireJList.setModel(new javax.swing.AbstractListModel<String>() {
        // String[] strings =driversString;//{ "Item 1", "Item 2", "Item 3", "Item 4",
        // "Item 5" };
        // public int getSize() { return strings.length; }
        // public String getElementAt(int i) { return strings[i]; }
        // });
      
        // hires
        
        DefaultListModel<String> model = new DefaultListModel<>();
        Hire[] hire = dispatch.getHiresData();
       
        for(int i = 0; i < hire.length; i++){
            model.addElement(hire[i].toString());
        }
        
        hireJList.setModel(model);

        hireListScrollPane.setViewportView(hireJList);

        driverJList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        //driverJList.setModel(new javax.swing.AbstractListModel<String>() {
        //    String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

       //     public int getSize() {
       //         return strings.length;
       //     }

        //    public String getElementAt(int i) {
       //         return strings[i];
        //    }
        //});

        //TODO: fix This with Dispatch Object
       model = new DefaultListModel<>();
       Driver[] drive = dispatch.getDriverOrganiser().toArray();

        for(int i = 0; i < drive.length; i++){
            model.addElement(drive[i].toString());
        }
        driverJList.setModel(model);
        
        driverListScrollPane.setViewportView(driverJList);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/proxima/view/Bundle"); // NOI18N
        hireLabel.setText(bundle.getString("proximaUI.hireLabel.text")); // NOI18N

        driverLabel.setText(bundle.getString("proximaUI.driverLabel.text")); // NOI18N

        assignDriverButton.setText(bundle.getString("proximaUI.assignDriverButton.text")); // NOI18N

        javax.swing.GroupLayout actorListPanelLayout = new javax.swing.GroupLayout(actorListPanel);
        actorListPanel.setLayout(actorListPanelLayout);
        actorListPanelLayout.setHorizontalGroup(
                actorListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hireListScrollPane)
                        .addGroup(actorListPanelLayout.createSequentialGroup()
                                .addGroup(actorListPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(driverListScrollPane)
                                        .addGroup(actorListPanelLayout.createSequentialGroup()
                                                .addContainerGap(108, Short.MAX_VALUE)
                                                .addComponent(assignDriverButton))
                                        .addGroup(actorListPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(actorListPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(hireLabel)
                                                        .addComponent(driverLabel))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        actorListPanelLayout.setVerticalGroup(
                actorListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(actorListPanelLayout.createSequentialGroup()
                                .addContainerGap(17, Short.MAX_VALUE)
                                .addComponent(hireLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hireListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assignDriverButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(driverLabel)
                                .addGap(4, 4, 4)
                                .addComponent(driverListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)));

        detailsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        detailsTextArea.setColumns(20);
        detailsTextArea.setRows(5);
        detailsScrollPane.setViewportView(detailsTextArea);

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
                detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addComponent(detailsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 505,
                                        Short.MAX_VALUE)
                                .addContainerGap()));
        detailsPanelLayout.setVerticalGroup(
                detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addComponent(detailsScrollPane)
                                .addContainerGap()));

        fileMenu.setText(bundle.getString("proximaUI.fileMenu.text")); // NOI18N

        saveMenuItem.setText(bundle.getString("proximaUI.saveMenuItem.text")); // NOI18N
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        exitMenuItem.setText(bundle.getString("proximaUI.exitMenuItem.text")); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(bundle.getString("proximaUI.helpMenu.text")); // NOI18N

        aboutMenuItem.setText(bundle.getString("proximaUI.aboutMenuItem.text")); // NOI18N
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(actorListPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(actorListPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(detailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(33, Short.MAX_VALUE)));
        this.setTitle("Proxima - The Taxi App");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_saveMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProximaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProximaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProximaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProximaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProximaUI().setVisible(true);
            }
        });

        

        // hires
        

        // map of streets
        StreetOrganiser map;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel actorListPanel;
    private javax.swing.JButton assignDriverButton;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JScrollPane detailsScrollPane;
    private javax.swing.JTextArea detailsTextArea;
    private javax.swing.JLabel driverLabel;
    private javax.swing.JList<String> driverJList;
    private javax.swing.JScrollPane driverListScrollPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel hireLabel;
    private javax.swing.JList<String> hireJList;
    private javax.swing.JScrollPane hireListScrollPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

    //Variables pertaining to Proxima
    private Dispatch dispatch;
    private Driver selectedDriver;
    private Hire selectedHire;


}
